version: '3.8'

services:
  frontend:
    image: rajaramachandran/eventdesk:frontend_v1
    environment:
      - NODE_ENV=production
    networks:
      - dokploy-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`eventdesk.io`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"

networks:
  eventdesk-network:
    driver: bridge
  dokploy-network:
    external: true
